# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Sonar Scan
        # You may pin to the exact commit or the version.
        # uses: sijomc/sonarscan-action@5a3a0c0eacbe76ac7c3e3513696f7449f4f914a5
        uses: sijomc/sonarscan-action@1.1
         with:
          # SonarQube server URL
          host: 
          # The project's unique key. Allowed characters are: letters, numbers, -, _, . and :, with at least one non-digit.
          projectKey: # optional, default is 
          # Name of the project that will be displayed on the web interface.
          projectName: # optional, default is 
          # The project version.
          projectVersion: # optional, default is 
          # Set the sonar.projectBaseDir analysis property
          projectBaseDir: # optional, default is .
          # Exclude directories from scanning
          exclusions: # optional
          # Login or authentication token of a SonarQube user
          login: 
          # Password that goes with the sonar.login username. This should be left blank if an authentication token is being used.
          password: # optional
          # Sonar Scanner options for memory optimization
          scannerOptions: # optional
