name: TFLint
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    environment: feenixdv-dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install TFLint
        run: |
          curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip
          unzip tflint.zip
          sudo mv tflint /usr/local/bin/

       
      - name: Run TFLint
        run: tflint
