name: TFLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tflint:
    name: TFLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install TFLint
        run: |
          curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip
          unzip tflint.zip
          sudo mv tflint /usr/local/bin/

      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: bibhutimail
          minimum-approvals: 1
          timeout-minutes: 300
          issue-title: "feenixdv-dev approver"
          issue-body: "Please approve or deny the deployment of lint"
          exclude-workflow-initiator-as-approver: false
          
      - name: Run TFLint
        run: tflint
